<?php 

class ProductTableSeeder extends Seeder {
 
    public function run()
    {
        DB::table('products')->insert(
 
            array(
                array(
                    'id' => 1,
                    'company_name' => 'Company1',
                    'name' => 'Product1',
                    'description' => 'This is the description of Product1',
                    'price' => '42',
                    'currency' => '$',
                    'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-11-25 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 2,
                    'company_name' => 'Company1',
                    'name' => 'Product2',
                    'description' => 'This is the description of Product2',
                    'price' => '4',
                    'currency' => '$',
					'media_id' => '1',
                    'status' => 'blocked',
					'created_at' => '2013-11-26 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 3,
                    'company_name' => 'Company1',
                    'name' => 'Product3',
                    'description' => 'This is the description of Product3',
                    'price' => '2',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-11-27 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 4,
                    'company_name' => 'Company2',
                    'name' => 'Product4',
                    'description' => 'This is the description of Product4',
                    'price' => '420',
                    'currency' => '$',
					'media_id' => '2',
                    'status' => 'blocked',
					'created_at' => '2013-11-28 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 5,
                    'company_name' => 'Company2',
                    'name' => 'Product5',
                    'description' => 'This is the description of Product5',
                    'price' => '402',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-12-25 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 6,
                    'company_name' => 'Company2',
                    'name' => 'Product6',
                    'description' => 'This is the description of Product6',
                    'price' => '421',
                    'currency' => '$',
					'media_id' => '1',
                    'status' => 'blocked',
					'created_at' => '2013-12-26 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 7,
                    'company_name' => 'Company3',
                    'name' => 'Product7',
                    'description' => 'This is the description of Product7',
                    'price' => '422',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-12-31 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 8,
                    'company_name' => 'Company2',
                    'name' => 'Product8',
                    'description' => 'This is the description of Product8',
                    'price' => '421',
                    'currency' => '$',
					'media_id' => '1',
                    'status' => 'blocked',
					'created_at' => '2013-12-26 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 9,
                    'company_name' => 'Company3',
                    'name' => 'Product9',
                    'description' => 'This is the description of Product9',
                    'price' => '422',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-12-31 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 10,
                    'company_name' => 'Company2',
                    'name' => 'Product10',
                    'description' => 'This is the description of Product10',
                    'price' => '421',
                    'currency' => '$',
					'media_id' => '1',
                    'status' => 'blocked',
					'created_at' => '2013-12-26 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 11,
                    'company_name' => 'Company3',
                    'name' => 'Product11',
                    'description' => 'This is the description of Product11',
                    'price' => '422',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-12-31 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 12,
                    'company_name' => 'Company3',
                    'name' => 'Product12',
                    'description' => 'This is the description of Product12',
                    'price' => '422',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-12-31 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 13,
                    'company_name' => 'Company1',
                    'name' => 'Product13',
                    'description' => 'This is the description of Product13',
                    'price' => '422',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-12-31 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 14,
                    'company_name' => 'Company2',
                    'name' => 'Product14',
                    'description' => 'This is the description of Product14',
                    'price' => '422',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-12-31 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
				array(
                    'id' => 15,
                    'company_name' => 'Company2',
                    'name' => 'Product15',
                    'description' => 'This is the description of Product15',
                    'price' => '422',
                    'currency' => '$',
					'media_id' => NULL,
                    'status' => 'free',
					'created_at' => '2013-12-31 00:00:00',
                    'updated_at' => '2014-01-01 00:00:00',					
                ),
            )
        );
    }
 
}

